version: '3'

services:
  ghost-hunter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghost-hunter
    ports:
      - "80:80"
      - "2222:22"
    restart: unless-stopped
    networks:
      - haunted_network

networks:
  haunted_network:
    driver: bridge 